### ISSUE TITLE
 '/logstash-conf.jar' contains no settings to import.

### ISSUE THREAD

**Issue by SuzanaK** [ycintre/intellij-logstash-conf-filetype#1]
I get the following when trying to import the settings:

```
The file '/logstash-conf.jar' contains no settings to import.
Please make sure you have generated the file using 'File|Export Settings' feature.
```

Using IntelliJ 2017.2.3

**Comment by rgmz** [comment]
Bump. :disappointed:

**Comment by awescarsoto** [comment]
I also ran into this when I right-clicked the link on the README and saved the file. You're actually supposed to click the link to go to be directed to the Github page where the jar is hosted. Once on there, you can Download the actual jar.

Alternatively, here's the direct link to download: https://github.com/ycintre/intellij-logstash-conf-filetype/raw/master/logstash-conf.jar

**Comment by ycintre** [comment]
Thanks for the tip!
I've updated the download link in the readme so you can right-click & use "Save link as..." to download the jar.

Note that the keyword list have not been updated in a while, some new keyword may be missing. I'll try to update it in the next few days.
